# Generated by Django 3.2.8 on 2021-10-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userhost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null='True')),
            ],
            options={
                'db_table': 'Hair_Category',
            },
        ),
    ]
